(cl:defpackage sphero_swarm_node-msg
  (:use )
  (:export
   "<SPHEROBACKLED>"
   "SPHEROBACKLED"
   "<SPHEROODOMETRY>"
   "SPHEROODOMETRY"
   "<SPHEROTURN>"
   "SPHEROTURN"
   "<SPHEROSWARMCOLLISION>"
   "SPHEROSWARMCOLLISION"
   "<SPHEROANGULARVELOCITY>"
   "SPHEROANGULARVELOCITY"
   "<SPHEROHEADING>"
   "SPHEROHEADING"
   "<SPHERODISABLESTABILIZATION>"
   "SPHERODISABLESTABILIZATION"
   "<SPHEROCOLOR>"
   "SPHEROCOLOR"
   "<SPHEROTWIST>"
   "SPHEROTWIST"
   "<SPHEROIMU>"
   "SPHEROIMU"
  ))

